Repository nibmcs/nibmcs.org, pull requests merged in 2023-10, with the labels that each got.

#1 Ci cd workflow
  .github/workflows/main.yml
  .gitignore
  .npmrc
  netlify.toml
  next.config.js
  package-lock.json
  package.json
  prebuild.js
  tsconfig.json
Labels: bug

#2 fix: PR deploy preview
  .github/workflows/main.yml
  .github/workflows/preview.yml
  netlify.toml
  next.config.js
  src/app/page.tsx
  tsconfig.json
Labels: enhancement

#3 docs: Add community standards
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/preview.yml
  CODE_OF_CONDUCT.md
  COMMIT_MESSAGE_GUIDELINES.md
  CONTRIBUTING.md
  LICENSE
Labels: documentation

#4 docs: Add SECURITY.md
  SECURITY.md
Labels: documentation

#6 feat: Add coming soon note
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
Labels: enhancement

#7 feat: Add new basic layout
  README.md
  package-lock.json
  package.json
  public/logo.png
  src/app/about/layout.tsx
  src/app/about/page.tsx
  src/app/blog/layout.tsx
  src/app/blog/page.tsx
  src/app/contact/layout.tsx
  src/app/contact/page.tsx
  src/app/events/layout.tsx
  src/app/events/page.tsx
  src/app/layout.tsx
  src/app/leaderboard/layout.tsx
  src/app/leaderboard/page.tsx
  src/app/membership/layout.tsx
  src/app/membership/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/Footer.tsx
  src/components/icons.tsx
  src/components/navbar.tsx
  src/components/theme-switch.tsx
  src/config/fonts.ts
  src/config/site.ts
Labels: enhancement, needs review, feature request

#16 fix: Change image for dark and light themes
  public/NCS-logo-color.png
  src/app/page.tsx
  src/components/icons.tsx
  src/components/navbar.tsx
Labels: enhancement, needs review

#19 feat: Add Vercel Web Analytics
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: enhancement, feature request

#20 docs: Update README.md
  README.md
Labels: documentation

#23 feat: Update contact page and navbar
  package-lock.json
  package.json
  public/NCS-logo-color.png
  public/logo.png
  src/app/about/layout.tsx
  src/app/about/page.tsx
  src/app/blog/layout.tsx
  src/app/blog/page.tsx
  src/app/contact/layout.tsx
  src/app/contact/page.tsx
  src/app/events/layout.tsx
  src/app/events/page.tsx
  src/app/layout.tsx
  src/app/leaderboard/layout.tsx
  src/app/leaderboard/page.tsx
  src/app/membership/layout.tsx
  src/app/membership/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/Footer.tsx
  src/components/box.tsx
  src/components/icons.tsx
  src/components/map.tsx
  src/components/navbar.tsx
  src/components/social.tsx
  src/components/theme-switch.tsx
  src/config/fonts.ts
  src/config/site.ts
  src/utils/variants.ts
Labels: enhancement, feature request
